const assert=require('node:assert/strict');
const {SectionGate}=require('../dist/section-holds.js');
const exits=[{id:'problem',top:800}];
const gate=new SectionGate();
assert.equal(gate.attempt(0,200,exits,1),null,'hero scroll must pass through');
assert.equal(gate.attempt(700,200,exits,2).id,'problem','first exit gesture stops');
assert.equal(gate.attempt(800,100,exits,2).id,'problem','momentum belongs to the blocked gesture');
assert.equal(gate.attempt(800,100,exits,3),null,'next gesture passes without a time delay');
assert.equal(gate.attempt(1700,200,exits,4),null,'long sections remain freely scrollable');
assert.equal(gate.attempt(1700,9999,exits,5),null,'all sections after the problem scroll freely');
gate.rewind(500,exits);
assert.equal(gate.attempt(700,200,exits,6).id,'problem','reverse scrolling re-arms section 2');
gate.release();assert.equal(gate.attempt(800,100,exits,6),null,'navigation can bypass the stop');
console.log('Section 2 gesture pause, immediate release, reverse scrolling and other-section bypass passed.');
